# Generated by Django 4.2.1 on 2023-05-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_price', models.CharField(max_length=50)),
                ('product_quantity', models.CharField(max_length=20)),
            ],
        ),
    ]
