# Generated by Django 4.2.1 on 2023-05-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
